### ISSUE TITLE
multi-asic support for config apply-patch and show runningconfig CLIs

### ISSUE THREAD

**Issue by anamehra** [sonic-net/sonic-buildimage#10857]
#### Description

sonic-mgmt testcase under generic_config_updater use config apply-patch for some of the test cases. config apply-patch does not handle multi-asic scenarios and that causes test cases to fail.

config apply-patch uses 'show runningconfig <>' command to fetch the running-config which also misses multi-asic support.

#### Steps to reproduce the issue:
1.
2.
3.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by anamehra** [comment]
@abdosi , FYI-

**Comment by abdosi** [comment]
@xincunli-sonic working on this. Please update this.

**Comment by xincunli-sonic** [comment]
1. Show runningconfiguration all change has merged in [public repo](https://github.com/sonic-net/sonic-utilities/pull/3148) and [chassis repo](https://github.com/sonic-net/sonic-utilities.msft/pull/45)
1. The supportive of multi asic GCU feature has merged into [public repo](https://github.com/sonic-net/sonic-utilities/pull/3249) and [chassis repo](https://github.com/sonic-net/sonic-utilities.msft/pull/64), but since there were multiple YANG files missing and wrong fields, the corresponding changes have being made and on their way to repo.
