### ISSUE TITLE
[VS] ARP packets are being dropped on the VS Image When used as a L2 device

### ISSUE THREAD

**Issue by vivekrnv** [sonic-net/sonic-buildimage#11381]
#### Steps to reproduce the issue:
1. Topology: HA <-> Eth0, HB <-> Eth4
2. config vlan add 10
3. config vlan member add 10 Ethernet0 -u
4. config vlan member add 10 Ethernet4 -u
5. Assign IP addresses in the same network to HA & HB
6. Ping HB from HA

#### Describe the results you received:
- ARP request is being dropped by the VS
- This is because of the ebtable rules configured.

These rules might be required on the real HW but these shouldn't be there for VS
```
-A FORWARD -p ARP -j DROP
-A FORWARD -p 802_1Q --vlan-encap ARP -j DROP
```

#### Describe the results you expected:
ARP shouldn't be dropped

#### Work-Around:

To allow ARP frames forwarded via the switch, please, remove corresponding ebtables entries:
```
sudo ebtables -D FORWARD -p 802_1Q --vlan-encap ARP -j DROP
sudo ebtables -D FORWARD -p ARP -j DROP
```

**Comment by prsunny** [comment]
This can be fixed by bypassing for the KVM image. Can be checked for platform in [build_debian.sh](https://github.com/Azure/sonic-buildimage/blob/master/build_debian.sh#L561) or [docker_image_ctl.j2](https://github.com/Azure/sonic-buildimage/blob/master/files/build_templates/docker_image_ctl.j2#L193). Request help from community.
