### ISSUE TITLE
[Build] Incorrect version (md5 hash) of web files in some conditions

### ISSUE THREAD

**Issue by kv-y** [sonic-net/sonic-buildimage#12279]
#### Description

We use curl and md5sum to calculate version of web file for reproducible build:
https://github.com/sonic-net/sonic-buildimage/blob/1f0699f51e51cf9ca6e36d85bc632ee0e31792e4/src/sonic-build-hooks/scripts/buildinfo_base.sh#L54-L58

The main issues here:
1. This action is not atomic. We use curl two times: for calculation md5sum and for downloading file after that.
https://github.com/sonic-net/sonic-buildimage/blob/1f0699f51e51cf9ca6e36d85bc632ee0e31792e4/src/sonic-build-hooks/scripts/buildinfo_base.sh#L128-L136
Possible solution here is using curl only once (at least when SONIC_VERSION_CONTROL_COMPONENTS=none) and calculate hash of already downloaded file.
2. If curl failed we save incorrect hash anyway in target/versions.

Short demonstration:

> ➜  ~ curl http://deb.debian.org/debian/pool/main/n/ntp/ntp_4.2.8p15+dfsg-1.debian.tar.xz | md5sum 
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Couldn't connect to server
> d41d8cd98f00b204e9800998ecf8427e  -

#### Steps to reproduce the issue:
1. Build with option SONIC_VERSION_CONTROL_COMPONENTS=none
2. Get some network troubles during this build
3. Check md5sum hashes of files in versions-web

#### Describe the results you received:
Curl failed for some reason at 1st step but incorrect hash (md5 of empty string - d41d8cd98f00b204e9800998ecf8427e) was saved to version-web file. At the same time build was not stopped, file was successfully downloaded at 2nd step and I noticed incorrect hash only after reviewing changes in file/build/versions.

#### Describe the results you expected:
If curl failed we should get an error.

**Comment by liushilongbuaa** [comment]
Using curl only once is better. We can use local file to caculate md5sum value.
Actually, we have a cache for downloaded files. If we have cached file with correct sha value, we will use cached file.
If not, we will use latest file in Internet. It is not a critical error.

**Comment by hisirbr** [comment]
Yes, it's not critical error. But it's important when we do UpgradeVersion. In this case we disable DPKG cache. So if curl fails then we got incorrect md5hash in target/versions though whole build was successful. Later when we'll try to update info in files/build/versions and will build with enabled SONIC_VERSION_CONTROL_COMPONENTS we'll catch this error.
As a quick fix I'm testing now solution like this:
`/usr/bin/curl -Lfks $package_url | md5sum | cut -d' ' -f1`
and then I compare result with d41d8cd98f00b204e9800998ecf8427e (md5 of empty string).
--fail flag allows to catch HTTP errors. Otherwise curl will generate some output and md5sum will use it to calculate incorrect md5sum.

But better solution here is refactoring and calculating hash of local files.

I think this bug is a rare case. But I faced with this two times so I decided to report about it.
