### ISSUE TITLE
Arista-7050QX-32S dmidecode - Scanning /dev/mem for entry point. # No SMBIOS nor DMI entry point found

### ISSUE THREAD

**Issue by jakubbdevops** [sonic-net/sonic-buildimage#15731]
```
SONiC Software Version: SONiC.master.308434-1dfe35cad
SONiC OS Version: 11
Distribution: Debian 11.7
Kernel: 5.10.0-18-2-amd64
Build commit: 1dfe35cad
Build date: Wed Jul  5 11:57:33 UTC 2023
Built by: AzDevOps@vmss-soni001GRI
```

```
Platform: x86_64-arista_7050_qx32s
HwSKU: Arista-7050QX-32S
ASIC: broadcom
ASIC Count: 1
Serial Number: SSJ17301008
Model Number: DCS-7050QX-32S
Hardware Revision: 02.00
Uptime: 15:52:48 up  7:08,  1 user,  load average: 0.37, 0.40, 0.45
Date: Thu 06 Jul 2023 15:52:48
admin@leaf1:~$ sudo /sbin/dmidecode
# dmidecode 3.3
Scanning /dev/mem for entry point.
# No SMBIOS nor DMI entry point found, sorry.
Hello, is it possible to have support of smbios infomartion in this switch? Is there missing something (modules etc) for this funcion? Or this will be not supported anymore on this HW?
```

Thanks a lot for Help

**Comment by Staphylo** [comment]
@jakubbdevops the BIOS of this system does not populate the `System Management BIOS` tables at boot.
Which is why the `dmidecode` tool is not able to find any information. This is unlikely to change for this soon to be EOL product.

Some of the information from `dmidecode` can be gathered in a few other ways:
 - `show platform syseeprom` for platform identification information
 - `/proc/cpuinfo` for cpu information
 - `decode-dimms` for ram information

**Comment by Staphylo** [comment]
Yes this is a limitation of this product and more specifically the BIOS.
Newer products might have SMBIOS information available but I haven't checked.

Yes SONiC has everything needed to access the SMBIOS information.
IIRC the `dmidecode` tool directly accesses `/dev/mem` and locate+parse the SMBIOS tables so I don't even believe the kernel is involved here (beside the availability of /dev/mem).

**Comment by jakubbdevops** [comment]
Thank you so much for your answers and mainly your time !

J.
