### ISSUE TITLE
Unable to Autogenerate  CLI using Auto generation tool for  Yang model during Build 

### ISSUE THREAD

**Issue by Purnimayeggina** [sonic-net/sonic-buildimage#16076]
Description:
Following the guide provided in the link https://github.com/sonic-net/SONiC/blob/master/doc/cli_auto_generation/cli_auto_generation.md.
We attempted to use the Auto Generation tool to obtain the CLI from the Yang model. As part of this process, we needed to trigger the ON/OFF switch for CLI auto-generation in the manifest.py file by making auto_generate_show and auto_generate_config to True  for the sonic-package-manager. The purpose of this action was to enable us to automatically generate the CLI for yang models during the build process, instead of having to do it manually for each yang model.

<img width="749" alt="image" src="https://github.com/sonic-net/SONiC/assets/131232786/3eb07980-3cd7-4688-ad8b-dd25e0927988">

<img width="563" alt="image" src="https://github.com/sonic-net/sonic-buildimage/assets/131232786/a2a52ded-a3a3-4cef-b2bb-581945e8b7b0">

However, we encountered an issue as we were unable to generate auto generated CLI even though we have done change by enabling in manifest.py file . We are uncertain whether we need to do any other changes, so that for all yang models there on board location /usr/local/yang-models will generate CLI by using CLI auto-generation tool in sonic-package-manager during build itself.

Steps to Reproduce:
Attempt to trigger CLI auto-generation from Yang models using the Auto Generation tool.
Look for the manifest.py file and do changes.
observe for the changes whether Auto generation tool generating CLI for all yang models for those yang models present in /usr/local/yang-models.

Expected Behavior:
After changing the manifest.py file in source need to auto-generate CLI for all yang models during build itself

**Comment by vadymhlushko-mlnx** [comment]
Hi @Purnimayeggina!

1. As specified in the HLD section [SONiC CLI Auto-generation tool as part of sonic-package-manager](https://github.com/sonic-net/SONiC/blob/master/doc/cli_auto_generation/cli_auto_generation.md#sonic-cli-auto-generation-tool-as-part-of-sonic-package-manager) the CLI autogeneration will only work when you are trying to `install` or `upgrade` the SONiC application extension. So, the CLI autogeneration is not available during the SONiC image build by design.

2. Not every YANG model is suitable for CLI autogeneration. For example, you cannot generate CLI for the: [sonic-types.yang](https://github.com/vadymhlushko-mlnx/sonic-buildimage/blob/master/src/sonic-yang-models/yang-templates/sonic-types.yang.j2), [sonic-extension.yang](https://github.com/vadymhlushko-mlnx/sonic-buildimage/blob/master/src/sonic-yang-models/yang-templates/sonic-extension.yang.j2)

3. If you are trying to autogenerate CLI for the feature in SONiC which already has a manually written CLI (by some developer), you should delete the existing CLI and then generate autogenerated CLI, because they will conflict with each other.

4. I'm not 100% sure that right now, you could autogenerate CLI for every YANG model, because YANG models have been changing over time, and maybe need to enhance the SONiC CLI Autogeneration tool accordingly

5. Please try to autogenerate CLI manually via the `sonic-cli-gen` tool for the YANG models that you're interested in, if there are some errors, send me an error itself, and the tech support dump, and I'll try to help

**Comment by vadymhlushko-mlnx** [comment]
@Purnimayeggina

1. As far as I understand, you are trying to do a sonic package upgrade from version X to version Y via `sonic-package-manager` or `spm`, could you please send me 2 files - manifest.json (version X) and manifest.json (version Y), so I will be able to help you.
2. Here you can find an example of [sonic-example-extension](https://github.com/stepanblyschak/sonic-example-extension)

**Comment by volodymyrsamotiy** [comment]
According to comment by @vadymhlushko-mlnx, it is expected behavior: CLI autogeneration is not available during the SONiC image build by design.
