### ISSUE TITLE
[Chassis] sonic-mgmt PC suite  tests test_voq_po_update and test_po_update_io_no_loss are failing

### ISSUE THREAD

**Issue by saksarav-nokia** [sonic-net/sonic-buildimage#19357]
#### Description
In latest master, the Port Channel test cases test_voq_po_update and test_po_update_io_no_loss are failing  and looks like it is due to the changes made in https://github.com/sonic-net/sonic-swss/pull/3150. 

When the empty LAG is created in one IMM, the oper status of the Lag is changed from unknown to down as shown in the logs below. When this oper state change notification is processed, the voqSyncIntfState is called which writes to the  SYSTEM_INTERFACE in chassis_db and the other asics in the same IMM  and other IMM's receives SYSTEM_LAG_TABLE & SYSTEM_INTERFACE notifications from chassis_db as shown below. The Router interface is created in remote asics and reference to the Lag.
But when the LAG is deleted, the local asic does not  delete the SYSTEM_INTERFACE and only deletes the SYSTEM_LAG_TABLE in chassis_db, so when the remote asics receives the SYSTEM_LAG_TABLE delete, it calls removeLag and since RouterInterface is referencing this lag, the delete fails and the  test cases fail. 
Does PortsOrch::updatePortOperStatusneed need to call  gIntfsOrch->voqSyncIntfStat when the oper state change from unknown to down?

2024 Jun 19 16:54:19.889094 ixre-egl-board7 NOTICE swss0#orchagent: :- addLag: Create an empty LAG PortChannel999 lid:2000000000c55
2024 Jun 19 16:54:19.889589 ixre-egl-board7 NOTICE swss0#orchagent: :- updatePortOperStatus: Port PortChannel999 oper state set from unknown to down
2024 Jun 19 16:54:19.889589 ixre-egl-board7 NOTICE swss0#orchagent: :- voqSyncIntfState: Syncing system interface state down for port ixre-egl-board7|asic0|PortChannel999
2024 Jun 19 16:54:19.891401 ixre-egl-board7 NOTICE swss1#orchagent: :- addLag: Create an empty LAG ixre-egl-board7|asic0|PortChannel999 lid:102000000000c0b
2024 Jun 19 16:54:19.897058 ixre-egl-board7 INFO kernel: [ 5084.526940] PortChannel999: Mode changed to "loadbalance"
2024 Jun 19 16:54:19.898792 ixre-egl-board7 NOTICE swss1#orchagent: :- addRouterIntfs: Create router interface ixre-egl-board7|asic0|PortChannel999 MTU 1492
2024 Jun 19 16:54:19.901126 ixre-egl-board7 NOTICE teamd0#teammgrd: :- addLag: Start port channel PortChannel999 with teamd
2024 Jun 19 16:54:19.904120 ixre-egl-board7 NOTICE swss0#portsyncd: :- onMsg: nlmsg type:16 key:PortChannel999 admin:1 oper:0 addr:40:7c:7d:bb:25:9d ifindex:62 master:0 type:team
2024 Jun 19 16:54:19.904969 ixre-egl-board7 NOTICE teamd0#teammgrd: :- setLagAdminStatus: Set port channel PortChannel999 admin status to up
2024 Jun 19 16:54:19.905031 ixre-egl-board7 INFO kernel: [ 5084.534338] 8021q: adding VLAN 0 to HW filter on device PortChannel999
2024 Jun 19 16:54:19.929936 ixre-egl-board7 NOTICE teamd0#teammgrd: :- setLagMtu: Set port channel PortChannel999 MTU to 9100
2024 Jun 19 16:54:19.930240 ixre-egl-board7 NOTICE teamd0#tlm_teamd: :- try_add_lag: The LAG 'PortChannel999' has been added.
2024 Jun 19 16:54:19.945668 ixre-egl-board7 NOTICE swss0#orchagent: :- updatePortOperStatus: Port PortChannel999 oper state set from down to down
2024 Jun 19 16:54:20.204105 ixre-egl-board7 NOTICE syncd1#syncd: :- addObject: Rif Counter oid:0x15100600003015 does not has supported counters

1) "pmessage"
2) "__keyspace@12__:*"
3) "__keyspace@12__:SYSTEM_LAG_TABLE|ixre-egl-board7|asic0|PortChannel999"
4) "hset"
1) "pmessage"
2) "__keyspace@12__:*"
3) "__keyspace@12__:SYSTEM_INTERFACE|ixre-egl-board7|asic0|PortChannel999"
4) "hset"
1) "pmessage"
2) "__keyspace@12__:*"
3) "__keyspace@12__:SYSTEM_LAG_ID_SET"
4) "srem"
1) "pmessage"
2) "__keyspace@12__:*"
3) "__keyspace@12__:SYSTEM_LAG_ID_TABLE"
4) "hdel"
1) "pmessage"
2) "__keyspace@12__:*"
3) "__keyspace@12__:SYSTEM_LAG_TABLE|ixre-egl-board7|asic0|PortChannel999"
4) "del"
^C(1057.04s)
 

#### Steps to reproduce the issue:
1. Run tests test_voq_po_update and test_po_update_io_no_loss in chassis
2.
3.

#### Describe the results you received:
The tests should pass
#### Describe the results you expected:
The tests are failing

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by judyjoseph** [comment]
@saksarav-nokia @arlakshm There was a PR recently to update the operstatus when addLag is done, will this help here?
https://github.com/sonic-net/sonic-swss/pull/3195

**Comment by arlakshm** [comment]
Hi @saksarav-nokia, regarding are below comment.
""But when the LAG is deleted, the local asic does not delete the SYSTEM_INTERFACE and only deletes the SYSTEM_LAG_TABLE in chassis_db, so when the remote asics receives the SYSTEM_LAG_TABLE delete, it calls removeLag and since RouterInterface is referencing this lag, the delete fails and the test cases fail."

If the lag is deleted without removing the ip interface on the local card. It is expected the remove lag will fail. this is existing design; it has nothing to do changes in https://github.com/sonic-net/sonic-swss/pull/3150. Please let me know if I am missing something?
'''
un 27 02:24:39.701624 str2-7804-lc3-1 NOTICE swss#orchagent: :- removeLagMember: Remove member Ethernet12 from LAG PortChannel101 lid:2000000000bef lmid:1b000000000bf1
Jun 27 02:24:48.899892 str2-7804-lc3-1 NOTICE teamd#teammgrd: :- removeLag: Stop port channel PortChannel101
Jun 27 02:24:48.901268 str2-7804-lc3-1 NOTICE swss#portsyncd: :- onMsg: nlmsg type:16 key:PortChannel101 admin:0 oper:0 addr:fc:bd:67:67:e4:1c ifindex:492 master:0 type:team
Jun 27 02:24:48.907396 str2-7804-lc3-1 NOTICE swss#portsyncd: :- onMsg: nlmsg type:17 key:PortChannel101 admin:0 oper:0 addr:fc:bd:67:67:e4:1c ifindex:492 master:0 type:team
Jun 27 02:24:48.911889 str2-7804-lc3-1 NOTICE swss#orchagent: :- updatePortOperStatus: Port PortChannel101 oper state set from down to down
Jun 27 02:24:48.912355 str2-7804-lc3-1 ERR teamd#tlm_teamd: :- get_dump: Can't get dump for LAG 'PortChannel101'. Skipping
Jun 27 02:24:48.913092 str2-7804-lc3-1 NOTICE teamd#tlm_teamd: :- remove_lag: The LAG 'PortChannel101' has been removed.
Jun 27 02:24:48.914067 str2-7804-lc3-1 NOTICE swss#orchagent: :- setRouterIntfsMtu: Set router interface PortChannel101 MTU to 9100
Jun 27 02:24:48.916115 str2-7804-lc3-1 ERR swss#orchagent: :- removeLag: Failed to remove ref count 4 LAG PortChannel101
'''

**Comment by saksarav-nokia** [comment]
@arlakshm , The test test_voq_po_update doesn't have ip address on the PortChannel999.  It creates empty lag and verifies in CHASSIS_DB and ASIC_DB and removes the lag.  The test was passing few week ago and started failing. 
            1. On any ASIC, add a new LAG
            2. verify added lag gets a unique lag id in chassis app db
            3. verify added lag exist in app db
            4. verify lag exist in asic db on remote and local asic db
            5. delete the added lag

**Comment by saksarav-nokia** [comment]
@arlakshm , With the following code commented out, the tests are passing
diff --git a/orchagent/portsorch.cpp b/orchagent/portsorch.cpp
index 40f79eb1..0f7e6529 100644
--- a/orchagent/portsorch.cpp
+++ b/orchagent/portsorch.cpp
@@ -8131,7 +8131,7 @@ void PortsOrch::updatePortOperStatus(Port &port, sai_port_oper_status_t status)
             SWSS_LOG_WARN("Inform nexthop operation failed for sub interface %s", child_port.c_str());
         }
     }
-
+#if 0
     if(gMySwitchType == "voq")
     {
         if (gIntfsOrch->isLocalSystemPortIntf(port.m_alias))
@@ -8139,6 +8139,7 @@ void PortsOrch::updatePortOperStatus(Port &port, sai_port_oper_status_t status)
             gIntfsOrch->voqSyncIntfState(port.m_alias, isUp);
         }
     }
+#endif
