### ISSUE TITLE
[chassis][202405]: Default hash-offset 0 causes ecmp load balancing failure on chassis-packet

### ISSUE THREAD

**Issue by anamehra** [sonic-net/sonic-buildimage#19746]
#### Description

switch.json in swss docker sets the default hash offset to 0 for chassis-packet. The change was recently introduced via https://github.com/sonic-net/sonic-buildimage/pull/18912 which was supposed to be only for T0/T1. On chassis-packet, each asics needs to set an unique hash offset to set an unique offset for load balancing algorithm. The new change overwrites platform setting and resets the hash-offset to 0 on all asics. This breaks the ecmp load balancing algorithm on chassis-packet.

#### Steps to reproduce the issue:
1.
2.
3.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by judyjoseph** [comment]
@kperumalbfn f.y.i trying to not set the default for chassis-packet

**Comment by kperumalbfn** [comment]
@anamehra For multi-asic and chassis platform, could you add the changes to sonic-swss code to apply hash_offset value using SAI attribute instead of setting inside platform code? I think that will be better instead of changes mentioned in PR - https://github.com/sonic-net/sonic-buildimage/pull/19745
