### ISSUE TITLE
Build sonic-slave-stretch image failed

### ISSUE THREAD

**Issue by OTaoZh** [sonic-net/sonic-buildimage#9768]
+++ Cheking platform/p4 +++
+++ Making configure +++
BLDENV=stretch make -f Makefile.work configure
make[1]: Entering directory '/home/sonic/ws/sonic-buildimage'
~/ws/sonic-buildimage/src/sonic-build-hooks ~/ws/sonic-buildimage
make[2]: Entering directory '/home/sonic/ws/sonic-buildimage/src/sonic-build-hooks'
dpkg-deb: building package 'sonic-build-hooks' in 'buildinfo/sonic-build-hooks_1.0_all.deb'.
make[2]: Leaving directory '/home/sonic/ws/sonic-buildimage/src/sonic-build-hooks'
~/ws/sonic-buildimage
Image sonic-slave-stretch:be98bf9a51b not found. Building...
Sending build context to Docker daemon    215kB
Step 1/63 : FROM debian:stretch
 ---> c599fc96ef79
Step 2/63 : MAINTAINER gulv@microsoft.com
 ---> Running in f9f6e56cd114
Removing intermediate container f9f6e56cd114
 ---> dcc9f902f1e1
Step 3/63 : COPY ["no-check-valid-until", "/etc/apt/apt.conf.d/"]
 ---> bf30e5036acc
Step 4/63 : COPY ["buildinfo", "/usr/local/share/buildinfo"]
 ---> c063ded20aa3
Step 5/63 : RUN dpkg -i /usr/local/share/buildinfo/sonic-build-hooks_1.0_all.deb
 ---> Running in ea8f81488cbb
dpkg-deb: error: archive '/usr/local/share/buildinfo/sonic-build-hooks_1.0_all.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive /usr/local/share/buildinfo/sonic-build-hooks_1.0_all.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 /usr/local/share/buildinfo/sonic-build-hooks_1.0_all.deb

**Comment by zhangyanzhao** [comment]
@OTaoZh can you please organize the info with the issue template? Thanks.

**Comment by antony-rheneus** [comment]
@zhangyanzhao , sonic-build-hooks debian packagage is built in the Host build Ubuntu and inside debian docker image, as there is dependency to be prebuilt before docker image building.  So the outcome is a Ubuntu sonic-build-hooks.deb package which is not the accurate debian version and may impact due to Debian vs Ubuntu compatibility issues. 

If the host Ubuntu version is not 16 or 18, this issue will be seen as Latest Ubuntu debian package moved to zst compression.

@OTaoZh 
Error is due to sonic-build-hooks debian package built in Host Build Ubuntu. For reference in this ticket please share your Build Host Ubuntu version by providing lsb_release output.
As SONIC recommends to use **Ubuntu 16**, please stick to it.

Or if you need fix for your build environment, uses dpkg-deb with -Zxz option for xz compression. below is the patch for it.

```
diff --git a/src/sonic-build-hooks/Makefile b/src/sonic-build-hooks/Makefile

@@ -19,9 +19,9 @@ DPKGTOOL = $(shell which dpg-deb)

  # If the depk-deb not installed, use the docker container to make the debian package
  ifeq ($(shell which dpkg-deb),)
- BUILD_COMMAND=docker run --user $(shell id -u):$(shell id -g) --rm -v $(shell pwd):/build debian:buster bash -c 'cd /build; dpkg-deb --build $(TMP_DIR)/$(SONIC_BUILD_HOOKS) $(SONIC_BUILD_HOOKS_TARGET)'
+ BUILD_COMMAND=docker run --user $(shell id -u):$(shell id -g) --rm -v $(shell pwd):/build debian:buster bash -c 'cd /build; dpkg-deb -Zxz --build $(TMP_DIR)/$(SONIC_BUILD_HOOKS) $(SONIC_BUILD_HOOKS_TARGET)'
  else
- BUILD_COMMAND=dpkg-deb --build $(TMP_DIR)/$(SONIC_BUILD_HOOKS) $(SONIC_BUILD_HOOKS_TARGET)
+ BUILD_COMMAND=dpkg-deb -Zxz --build $(TMP_DIR)/$(SONIC_BUILD_HOOKS) $(SONIC_BUILD_HOOKS_TARGET)
endif
```

**Comment by judyjoseph** [comment]
@xumia I am seeing this fix might be needed in our 202205 branches as well ? Esp I found this patch (adding the option -Zxz ) useful to fix the issue with internal-202205-chassis branch )

**Comment by xumia** [comment]
> @xumia I am seeing this fix might be needed in our 202205 branches as well ? Esp I found this patch (adding the option -Zxz ) useful to fix the issue with internal-202205-chassis branch )

Added the cherry-pick request for the old releases.

https://github.com/sonic-net/sonic-buildimage/pull/12823
